### ISSUE TITLE
Naming Convention for the files 

### ISSUE THREAD

**Issue by reirembar** [sashalex007/tennis-racquet-custom-pallets#1]
Hi there,
I would like first to thank you for putting on the work and make this publicly available. However, I would like to ask you if the file ezone98_head1:4 is to print a head handle (sized #2) to put on an ezone raquect or the other way around? That is my guess but I want to make sure of your naming convention here. 
My intention is to modify a Tecnifibre TF40, which has more of a rectangular shape in the handle. A Wilson or Yonex handle would be more of my liking. I am looking around the internet to find which of the pallets that you post here would better take a Tecnifibre hairpin but there is little information floating on internet on modifiying Tecnifibre raquects. I might have to end up playing a guessing game here.
Thank you!!!

**Comment by sashalex007** [comment]
Hi,

You are correct about the naming- ezone98_head1:4 is indeed a head 1/4" pallet for the ezone98 hairpin. I don't have any information about Tecnifibre hairpins however I can tell you that wilson and yonex hairpins are vastly different. I would guess that neither would be suitable for a Tecnifibre. 

The only way to know is to expose the hairpin and do a direct compare, but more likely you will end up having to take the dimensions of the Tecnifibre hairpin and modify one of my models.

I hope that helps

**Comment by reirembar** [comment]
Hello,
Thank you so much for taking the time to answer my question. I really appreciate it.
All that you say make sense and I supposed it already, but I thought that it wouldn't hurt to ask. I have never worked with 3D printing so modifying one of your models seems a little bit far fetched righ now, but if I ever make any progress in this regard, by myself or with some help, I will let you know and maybe you could add a little more to this project. 
Those Tecnifibre racquets are really good, specially the TF40, and it is a shame that I struggle so much with the handle they put on it with my semiwestern grip. I know other people with the same problem and my guess is that many other would benefit from being able to modify that handle. Maybe even Tecnifibre benefits by selling a little more racquets!!! :)
Thanks again.
